# example values
server:
 port: 8080

spring:
 datasource:
    username: root
    password: 97nastya
    url: jdbc:mysql://localhost:3306/search_engine
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#      generate-ddl: true
    show-sql: true


indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru