# example values
server:
 port: 8080

spring:
 datasource:
    username: root
    password: 97nastya
    url: jdbc:mysql://localhost:3306/
      search_engine?useSSL=false
      &requireSSL=false
      &allowPublicKeyRetrieval=true&characterEncoding=utf8
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level.root: INFO
  file.name: logs/info.log

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru